/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* ── Light Minimal Palette ── */
        "on-error": "#ffffff",
        "error": "#f43f5e",
        "inverse-on-surface": "#f8f8ff",
        "on-tertiary-fixed-variant": "#065f46",
        "on-surface": "#1e1b2e",
        "outline-variant": "#ddd8f0",
        "background": "#f5f4ff",
        "surface-variant": "#ede9ff",
        "secondary-fixed-dim": "#c7c3dd",
        "tertiary-fixed-dim": "#6ee7b7",
        "surface-container-high": "#ede9ff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#e0dff7",
        "secondary-container": "#ede9ff",
        "on-secondary-fixed-variant": "#4c4870",
        "on-primary-fixed-variant": "#3730a3",
        "error-container": "#ffe4e6",
        "inverse-primary": "#a5b4fc",
        "on-primary-fixed": "#1e1b4b",
        "primary-fixed": "#e0e7ff",
        "inverse-surface": "#2d2b3d",
        "tertiary": "#10b981",
        "primary": "#6366f1",
        "on-secondary-container": "#4c4870",
        "on-primary-container": "#ffffff",
        "tertiary-container": "#34d399",
        "on-tertiary": "#ffffff",
        "on-background": "#1e1b2e",
        "surface": "#fafafe",
        "on-secondary-fixed": "#1e1b2e",
        "surface-bright": "#ffffff",
        "on-primary": "#ffffff",
        "primary-container": "#818cf8",
        "on-surface-variant": "#6b7280",
        "surface-tint": "#6366f1",
        "on-secondary": "#ffffff",
        "secondary": "#8b5cf6",
        "on-tertiary-fixed": "#022c22",
        "on-tertiary-container": "#ffffff",
        "primary-fixed-dim": "#a5b4fc",
        "surface-container-low": "#f5f4ff",
        "surface-container-highest": "#ddd8f0",
        "outline": "#9ca3af",
        "on-error-container": "#be123c",
        "secondary-fixed": "#ede9ff",
        "tertiary-fixed": "#a7f3d0",
        "surface-container": "#eeedfa"
      },
      fontFamily: {
        "headline": ["Outfit", "Inter", "system-ui", "sans-serif"],
        "display": ["Outfit", "Inter", "system-ui", "sans-serif"],
        "body": ["Inter", "system-ui", "sans-serif"],
        "label": ["Inter", "system-ui", "sans-serif"],
        "numeric": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem", 
        "md": "0.375rem",
        "lg": "0.5rem", 
        "xl": "0.75rem", 
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      boxShadow: {
        "glow-primary": "0 8px 32px -8px rgba(99, 102, 241, 0.35)",
        "glow-soft": "0 4px 24px -4px rgba(99, 102, 241, 0.15)",
        "glass": "0 8px 32px rgba(15, 23, 42, 0.06), inset 0 1px 0 rgba(255, 255, 255, 0.9)",
      },
      backdropBlur: {
        xs: "2px",
      },
      keyframes: {
        "ambient-drift": {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "33%": { transform: "translate(3%, -2%) scale(1.03)" },
          "66%": { transform: "translate(-2%, 2%) scale(0.98)" },
        },
      },
      animation: {
        "ambient-drift": "ambient-drift 24s ease-in-out infinite",
      },
    },
  },
  plugins: [],
}
